[package]
name = "gateway"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
control = { version = "0.1.0", path = "../control" }
devices = { version = "0.1.0", path = "../devices" }
iec104 = { version = "0.1.0", path = "../iec104", features = ["tokio"] }
rustls-pki-types = { optional = true, version = "1.15.1", features = ["std"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tokio-modbus = { version = "0.17.0", default-features = false, features = ["tcp"] }
tokio-rustls = { optional = true, version = "0.26.5", default-features = false, features = ["ring", "logging", "tls12"] }
toml = "1.1.6"
tower-http = { version = "0.7.1", features = ["fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[features]
default = ["tls"]
tls = ["dep:tokio-rustls", "dep:rustls-pki-types"]
